import type { Banco } from '@/app/types'

export const BANCOS: Banco[] = [
  {
    id: 'boveda_monte',
    nombre: 'Bóveda Monte',
    icon: 'building',
    color: 'from-blue-500 to-cyan-500',
    tipo: 'boveda',
    descripcion: 'Capital principal de operaciones',
    moneda: 'MXN',
    capitalActual: 2450000,
    capitalInicial: 2000000,
    historicoIngresos: 5000000,
    historicoGastos: 2550000,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'boveda_usa',
    nombre: 'Bóveda USA',
    icon: 'flag',
    color: 'from-red-500 to-blue-500',
    tipo: 'boveda',
    descripcion: 'Capital en dólares/USA',
    moneda: 'USD',
    capitalActual: 128005,
    capitalInicial: 100000,
    historicoIngresos: 200000,
    historicoGastos: 71995,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'utilidades',
    nombre: 'Utilidades',
    icon: 'diamond',
    color: 'from-green-500 to-emerald-500',
    tipo: 'utilidades',
    descripcion: 'Ganancias netas del negocio',
    moneda: 'MXN',
    capitalActual: 102658,
    capitalInicial: 0,
    historicoIngresos: 150000,
    historicoGastos: 47342,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'flete_sur',
    nombre: 'Flete Sur',
    icon: 'truck',
    color: 'from-orange-500 to-amber-500',
    tipo: 'gastos',
    descripcion: 'Capital para gastos de transporte',
    moneda: 'MXN',
    capitalActual: 185792,
    capitalInicial: 200000,
    historicoIngresos: 250000,
    historicoGastos: 64208,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'azteca',
    nombre: 'Azteca',
    icon: 'store',
    color: 'from-purple-500 to-pink-500',
    tipo: 'operativo',
    descripcion: 'Cuenta bancaria externa Azteca',
    moneda: 'MXN',
    capitalActual: -178715,
    capitalInicial: 50000,
    historicoIngresos: 50000,
    historicoGastos: 228715,
    historicoTransferencias: 0,
    estado: 'negativo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'leftie',
    nombre: 'Leftie',
    icon: 'briefcase',
    color: 'from-yellow-500 to-orange-500',
    tipo: 'operativo',
    descripcion: 'Capital de negocio secundario',
    moneda: 'MXN',
    capitalActual: 45844,
    capitalInicial: 50000,
    historicoIngresos: 80000,
    historicoGastos: 34156,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'profit',
    nombre: 'Profit',
    icon: 'trending-up',
    color: 'from-indigo-500 to-purple-500',
    tipo: 'operativo',
    descripcion: 'Utilidades distribuidas',
    moneda: 'MXN',
    capitalActual: 12577748,
    capitalInicial: 10000000,
    historicoIngresos: 15000000,
    historicoGastos: 2422252,
    historicoTransferencias: 0,
    estado: 'activo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const MOCK_DATA = {
  ventasHoy: 247500,
  ventasAyer: 215000,
  ordenesPendientes: 23,
  stockCritico: 12,
  capitalTotal: 18473020,
  capitalMesAnterior: 17000000,
}
