import type { Banco } from "@/types"

export const BANCOS: Banco[] = [
  {
    id: "boveda-monte",
    nombre: "Bóveda Monte",
    icon: "building",
    color: "from-blue-500 to-cyan-500",
    tipo: "operativo",
    descripcion: "Capital principal de operaciones",
    capitalActual: 2450000,
    historicoIngresos: 5000000,
    historicoGastos: 2550000,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "boveda-usa",
    nombre: "Bóveda USA",
    icon: "flag",
    color: "from-red-500 to-blue-500",
    tipo: "operativo",
    descripcion: "Capital en dólares/USA",
    capitalActual: 128005,
    historicoIngresos: 200000,
    historicoGastos: 71995,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "utilidades",
    nombre: "Utilidades",
    icon: "diamond",
    color: "from-green-500 to-emerald-500",
    tipo: "inversion",
    descripcion: "Ganancias netas del negocio",
    capitalActual: 102658,
    historicoIngresos: 150000,
    historicoGastos: 47342,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "fletes",
    nombre: "Fletes",
    icon: "truck",
    color: "from-orange-500 to-amber-500",
    tipo: "operativo",
    descripcion: "Capital para gastos de transporte",
    capitalActual: 185792,
    historicoIngresos: 250000,
    historicoGastos: 64208,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "azteca",
    nombre: "Azteca",
    icon: "store",
    color: "from-purple-500 to-pink-500",
    tipo: "externo",
    descripcion: "Cuenta bancaria externa Azteca",
    capitalActual: -178715,
    historicoIngresos: 50000,
    historicoGastos: 228715,
    historicoTransferencias: 0,
    estado: "negativo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "leftie",
    nombre: "Leftie",
    icon: "briefcase",
    color: "from-yellow-500 to-orange-500",
    tipo: "externo",
    descripcion: "Capital de negocio secundario",
    capitalActual: 45844,
    historicoIngresos: 80000,
    historicoGastos: 34156,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "profit",
    nombre: "Profit",
    icon: "trending-up",
    color: "from-indigo-500 to-purple-500",
    tipo: "inversion",
    descripcion: "Utilidades distribuidas",
    capitalActual: 12577748,
    historicoIngresos: 15000000,
    historicoGastos: 2422252,
    historicoTransferencias: 0,
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const MOCK_DATA = {
  ventasHoy: 247500,
  ventasAyer: 215000,
  ordenesPendientes: 23,
  stockCritico: 12,
  capitalTotal: 18473020,
  capitalMesAnterior: 17000000,
}
