type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Workspace @table {
  name: String!
  createdAt: Timestamp!
  owner: User!
  description: String
}

type Project @table {
  name: String!
  createdAt: Timestamp!
  workspace: Workspace!
  description: String
  dueDate: Date
}

type Asset @table {
  name: String!
  assetType: String!
  createdAt: Timestamp!
  workspace: Workspace!
  description: String
  fileUrl: String
}

type Task @table {
  title: String!
  status: String!
  createdAt: Timestamp!
  project: Project!
  assignedTo: User
  description: String
  dueDate: Date
}