/**
 * Utils - Exportaciones centralizadas
 * Sistema Chronos
 */

// Cálculos de negocio
export {
  calcularDistribucionVenta,
  calcularCostoTotalOrden,
  calcularMargenBruto,
  calcularMargenNeto,
  calcularPorcentajeMargen,
  calcularRentabilidad,
  calcularAnalisisMargen,
  calcularDeudaOrden,
  calcularValorInventario,
  calcularCapitalTotal,
  calcularCrecimiento,
  proyectarVentas,
  calcularDeudaTotalClientes,
  calcularDiasMora,
  formatearMoneda,
  formatearPorcentaje,
  formatearNumero,
  redondear,
  type VentaData,
  type OrdenCompraData,
  type DistribucionVenta,
  type MargenCalculo,
  type ProyeccionData,
} from './calculations';

// Default export de calculations
export { default as business } from './calculations';

// Validadores Zod
export {
  ordenCompraSchema,
  ventaSchema,
  transferenciaSchema,
  clienteSchema,
  distribuidorSchema,
  productoSchema,
  movimientoAlmacenSchema,
  bancoSchema,
  gastoSchema,
  abonoClienteSchema,
  abonoDistribuidorSchema,
  loginSchema,
  registroSchema,
  filtroReporteSchema,
  reporteProgramadoSchema,
  validarDatos,
  validarCampo,
  sanitizarString,
  normalizarNombre,
  formatearTelefono,
  schemas,
  type OrdenCompraInput,
  type VentaInput,
  type TransferenciaInput,
  type ClienteInput,
  type DistribuidorInput,
  type ProductoInput,
  type MovimientoAlmacenInput,
  type BancoInput,
  type GastoInput,
  type AbonoClienteInput,
  type AbonoDistribuidorInput,
  type LoginInput,
  type RegistroInput,
  type FiltroReporteInput,
  type ReporteProgramadoInput,
} from './validators';

// Formateadores
export {
  formatCurrency,
  formatMXN,
  formatUSD,
  formatCompact,
  parseCurrency,
  formatNumber,
  formatPercent,
  formatChange,
  formatQuantity,
  formatDate,
  formatTime,
  formatRelativeTime,
  formatDuration,
  formatDateRange,
  capitalize,
  titleCase,
  truncate,
  formatName,
  formatPhone,
  formatStatus,
  formatFileSize,
  formatList,
  currency,
  number,
  date,
  text,
  file,
} from './formatters';
